config/routes.rb
Rails.application.routes.draw do
  resources :stories do
  	resources :chaps
  end
  resources :stories do 
  	resources :comments
  end
  devise_for :users
  resources :users, only: [:show]
  root "stories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chap.rb
class Chap < ApplicationRecord
  belongs_to :story
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :chaps, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  def self.search(search)
	  where("name LIKE ?",  "%#{search}%") 
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chaps_controller.rb
class ChapsController < ApplicationController
  before_action :find_story
  before_action :authenticate_user!, except: [:show]

  def show

  	@chap = Chap.find(params[:id]) 
    id_list = @story.chaps.ids.sort
    # # id_list = []
    # # @story.chaps.each do |chap|
    # #   id_list << chap.id
    # # end
    # # id_list.sort! 
    # i = @chap.id
    # # j = id_list.index(i)
    # if i == id_list.last
    #   @next_chap = nil
    # else 
    #   j = id_list.detect{|e| e > i}
    #   @next_chap = Chap.find(j)
    #   # @next_chap = @story.chaps.where(id: i)
    # end

    # if i == id_list.first 
    #   @previous_chap = nil
    # else
    #   j = id_list.detect{|e| e < i}
    #   @previous_chap = Chap.find(j) 
    # end
    @next_chap_id = id_list.detect { |e| e > @chap.id.to_i }
    @previous_chap_id = id_list.reverse.detect{ |e| e < @chap.id}
  end
  def new
  end

  def create
  	@chap = @story.chaps.create(chap_params)
  	if @chap.save
  	  redirect_to story_chap_path(@story, @chap.id)
  	else
  		render 'new'
  	end
  end

  def edit
  	@chap = @story.chaps.find(params[:id])
  end

  def update
  	@chap = @story.chaps.find(params[:id])
  	if @chap.update(chap_params)
  		redirect_to story_chap_path(@story, @chap.id)
  	else
  		render 'edit'
  	end
  end

  def destroy
    @chap = @story.chaps.find(params[:id])
    @chap.destroy
    redirect_to story_path(@story)
  end

  private
  def find_story
  	@story = Story.find(params[:story_id])
  end

  def chap_params
  	params.require(:chap).permit(:name, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_user
	def create
    @story = Story.find(params[:story_id])
    
    @comment = @story.comments.create(comment_params)
    @comment.name = current_user.email
    @comment.save
    redirect_to story_path(@story)
  end

  def edit
  	@comment = @story.comments.find(params[:id])
  end

  def update
  	@comment = @story.comments.find(params[:id])
  	@comment.update(comment_params)
  	redirect_to story_path(@story)
  end
	
  def destroy
    @story = Story.find(params[:story_id])
    @comment = @story.comments.find(params[:id])
    @comment.destroy
    redirect_to story_path(@story)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:content, :name)
    end

    def find_user
    	@user = current_user
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_cookies, only: [:show]
  # GET /stories
  # GET /stories.json
  def index
   
    @stories = Story.all
    if params[:search]
      @stories = Story.search(params[:search]).order("created_at DESC")
    else
      @stories = Story.all.order("created_at DESC")
    end

  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  	# binding.pry
    @story.reader = @story.reader + 1
    @story.save
  end

  # GET /stories/new
  def new
    @story = current_user.stories.build
  end

  # GET /stories/1/edit
  def edit
  end
      
  # POST /stories
  # POST /stories.json
  def create
    
    @story = current_user.stories.build(story_params)
    @story.reader = 0
    @story.save

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:name, :descripton, :author, :image, :story_type) 
    end

    def set_cookies
      if user_signed_in?
        if cookies[:nearest_stories].blank?
          cookies[:nearest_stories] = []
          cookies[:nearest_stories] << {:user_email => current_user.email, :story_id => @story.id.to_s}
          cookies[:nearest_stories] = cookies[:nearest_stories].to_json
        else
        	
          cookies[:nearest_stories] = JSON.load(cookies[:nearest_stories])
          a = {:user_email => current_user.email, :story_id => @story.id.to_s}
          if cookies[:nearest_stories].include?(a) == false
            cookies[:nearest_stories].unshift(a)
            cookies[:nearest_stories].delete_at(5) if cookies[:nearest_stories].length >= 5
          end
          cookies[:nearest_stories] = cookies[:nearest_stories].to_json
        end
      end
    end
end   

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chaps_helper.rb
module ChapsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chaps/_form.html.erb
<%= form_with(model: [ @story, @story.chaps.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p  >
    <%= form.label :content %><br>
    <%= form.text_area :content%>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/chaps/edit.html.erb
<h2>Edit your chap:</h2>
<%= form_with(model: [ @story, @chap], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit "Update" %>
  </p>
<% end %>

app/views/chaps/new.html.erb
<h1 style = "text-align: center">Create new chap</h1>
<%= render 'form' %>

app/views/chaps/show.html.erb
<div class="container">
	<h1 style = "text-align: center"><%= link_to @story.name, story_path(@story) %></h1>
	<h1 style = "text-align: center"><%= @chap.name %></h1>
	<%= link_to 'Edit', edit_story_chap_path(@story, @chap.id) %> 
	<%= link_to 'Destroy Chap', story_chap_path(@story, @chap.id), :class => "edit",
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %><br>

	<p class = "chap-content"><%= @chap.content %></p>


	<p class = "next"><% if @previous_chap_id != nil %>
	<%= link_to 'Previous', story_chap_path(@story, @previous_chap_id) %>
	<% end %>
	|
	<% if @next_chap_id != nil %>
	<%= link_to 'Next', story_chap_path(@story, @next_chap_id) %>
	<% end %><br></p>

	<%= link_to 'Back', story_path(@story) %>
</div>

app/views/comments/_comment.html.erb
<h2>Comments</h2>
<% @story.comments.each do |comment| %>
	<p>
	  <strong><%= comment.name %></strong>: <%= comment.content %>  
	<% if user_signed_in? && current_user.email == comment.name %>
		<%= link_to 'Delete comment', [comment.story, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
	<% end %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [ @story, @story.comments.build ], local: true) do |form| %>
	<p><%= current_user.email %>:</p>
	<p>
		<%= form.text_area :content %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to image_tag("https://imgur.com/3y2fo1S", :class => "logo img-responsive"), stories_path, {:style =>'padding: 0'} %></li>
            <li class = "link"><%= link_to("The loai", "#") %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li> 
            <% else %>
              <li><%= link_to("Sign_in", new_user_session_path) %></li>
              <li><%= link_to("Sign_up", new_user_registration_path) %></li>
            <% end %>
          </ul>
          <!-- <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form> -->

          <%= form_tag(stories_path, :method => "get", id: "search-form", :class => "navbar-form navbar-right") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Story" %>
            <%= submit_tag "Search", :name => nil %>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav> 

    <h3 class = "container description"> The page reading stories for you </h3>

    <%= yield %>
    <hr>
    <div class="container footer">
      <div class="row">        
        <div class="col-md-6 col-lg-6">
          <p>This website is a demo of rails app</p>
        </div> 
        <div class="col-md-6 col-lg-6">
          <p>Email: 123456@gmail.com</p>
          <p>Adress</p>
        </div>      
      </div>   
    </div>

  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :descripton %>
    <%= form.text_area :descripton %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div id = "check-box" class="field">
    <%= form.label :story_type %><br>

    
    <%= check_box_tag "story[story_type]", value = "do thi", :id => "do_thi"%> Do thi <br>
    <%= check_box_tag "story[story_type]", value = "sac", :id => "sac" %> Sac <br>
    <%= check_box_tag "story[story_type]", value = "huyen huyen", :id => "huyen_huyen" %> Huyen huyen <br>
    <%= check_box_tag "story[story_type]", value = "ngon tinh", :id => "ngon_tinh" %> Ngon tinh <br>
  </div>

  <div>
    <%= form.file_field :image %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/_hot_form.html.erb
<ul class="read-stories">
	<% @stories.each do |story| %>
		
	    <div class="col-md-4 col-lg-4 thumbnail anh">
	      <%= link_to image_tag(story.image.url), story_path(story), :class => "story-img img-responsive "%>
	      <%= link_to story.name, story_path(story),:class => "story" %>
	    </div>  
	
  <% end %>
</ul>  

app/views/stories/_most_read_story.html.erb
<h2> Most read story </h2>
<% a = Story.all.map { |s| [s.id, s.reader]} %>
<% b = a.sort_by{|x,y| y}.reverse! %>
<ul>
	<% for i in 0..4 do %>
		<% s = Story.find(b[i][0]) %>
		<li><%= link_to s.name, story_path(s) %></li>
	<% end %>
</ul>

app/views/stories/_read_form.html.erb
<h2><%= link_to "Truyen da doc" , "#" %></h2>
<!-- <ul class="read-stories">
	<% @stories.each do |story| %>
		<li><%= link_to story.name, story_path(story),:class => "read-story" %></li>
	<% end %>
</ul>   -->
<ul>
<% if user_signed_in? && cookies[:nearest_stories] != nil %>


	<% JSON.load(cookies[:nearest_stories]).each do |st|%>
		<% s = Story.find(st["story_id"].to_i) %>
		<li><%= link_to s.name, story_path(s) %></li>
	<% end %>

<% end %>
</ul>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>
<h1 style = "text-align: center;">Stories</h1>
<% if user_signed_in?  %>
  <%= link_to 'Go to your page', user_path(current_user) %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-lg-8 content">
      <h2><%= link_to "Truyen hot" , "#" %></h2>
      <%= render 'hot_form' %>
    </div>
    <div class="col-md-3 col-lg-3 read_form">
      <%= render 'read_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-lg-8 content">
      <h2><%= link_to "Truyen Tien Hiep" , "#" %></h2>
      <%= render 'hot_form' %>
    </div>
    <div class="col-md-3 col-lg-3 read_form">
      <%= render 'most_read_story' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-lg-8 content">
      <h2><%= link_to "Truyen Ngon Tinh" , "#" %></h2>
      <%= render 'hot_form' %>
    </div>
  </div>
</div>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<% if @story.user == current_user  %>
	  <%= link_to 'Edit', edit_story_path(@story, :class => "edit") %>
	  <%= link_to 'Destroy', @story, :class => "edit", method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
	<%= image_tag @story.image.url %>
	<h2 style = "text-align: center; color: red"> 
	  <%= @story.name %>
	</h2>	
	<p style = "text-align: left; font-size: 18px; line-height: 1.7"> 
	  <%= @story.descripton %>
	</p>

	<p>
	  <strong>Author:</strong>
	  <%= @story.author %>
	</p>

	<% @story.chaps.each do |chap| %>
	  <p><%= link_to chap.name, story_chap_path(@story, chap.id) %></p>
	  
	<% end %>

	<%= render 'comments/comment' %>

	<% if user_signed_in? %>
		<h2>Add a comment:</h2>
		<%= render 'comments/form' %>
	<% end %>
	
	<% if @story.user == current_user %>
	  <%= link_to 'Add new chap', new_story_chap_path(@story) %>
	<% end %>
	<br>
	<%= link_to 'Edit', edit_story_path(@story) %> |
	<%= link_to 'Back', stories_path %>
</div>
	
	

app/views/users/show.html.erb
<% if user_signed_in?	 %>
	<h1 style = "text-align: center">Welcom <%= current_user.email %></h1>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Story Name</th>
				<th>Add new chap</th>
				<th>Chap</th>
				<th>Date</th>
				<th>Views</th>
			</tr>
		</thead>
		<tbody>
				<% current_user.stories.each do |story|%>
				<tr>
					<td><%= link_to story.name, story_path(story) %></td>
					<td><%= link_to 'Add new chap', new_story_chap_path(story) %></td>
					<td>
						<% if story.chaps.blank? %>
							<%= link_to 'Add new chap', new_story_chap_path(story) %>
						<% else %>
							<%= link_to story.chaps.last.name, story_chap_path(story, story.chaps.last) %>
						<% end %>
					</td>
					<td><%= story.created_at %></td>
					<td><%= story.reader %></td>
				</tr>
				<% end %>
		</tbody>
	</table>
<% end %>